// Generated by Haxe 4.3.7

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.io {
	public class Input : global::haxe.lang.HxObject {
		
		public Input(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Input() {
			global::haxe.io.Input.__hx_ctor_haxe_io_Input(this);
		}
		
		
		protected static void __hx_ctor_haxe_io_Input(global::haxe.io.Input __hx_this) {
		}
		
		
		public virtual int readByte() {
			unchecked {
				throw new global::haxe.exceptions.NotImplementedException(default(string), default(global::haxe.Exception), ((object) (new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"readByte", "haxe.io.Input", "haxe/io/Input.hx"}, new int[]{1981972957}, new double[]{((double) (53) )})) ));
			}
		}
		
		
		public virtual string readLine() {
			unchecked {
				global::haxe.io.BytesBuffer buf = new global::haxe.io.BytesBuffer();
				int last = default(int);
				string s = null;
				try {
					while (true) {
						last = this.readByte();
						if ( ! ((( last != 10 ))) ) {
							break;
						}
						
						( buf.b as global::System.IO.Stream ).WriteByte(((byte) (last) ));
					}
					
					s = buf.getBytes().toString();
					if (global::haxe.lang.Runtime.eq((global::haxe.lang.StringExt.charCodeAt(s, ( s.Length - 1 ))).toDynamic(), 13)) {
						s = global::haxe.lang.StringExt.substr(s, 0, new global::haxe.lang.Null<int>(-1, true));
					}
					
				}
				catch (global::System.Exception _g){
					object _g1 = global::haxe.Exception.caught(_g).unwrap();
					if (( _g1 is global::haxe.io.Eof )) {
						global::haxe.io.Eof e = ((global::haxe.io.Eof) (_g1) );
						{
							s = buf.getBytes().toString();
							if (( s.Length == 0 )) {
								throw ((global::System.Exception) (global::haxe.Exception.thrown(e)) );
							}
							
						}
						
					}
					else {
						throw;
					}
					
				}
				
				
				return s;
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1873474154:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "readLine", 1873474154)) );
					}
					
					
					case 1763375486:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "readByte", 1763375486)) );
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				switch (hash) {
					case 1873474154:
					{
						return this.readLine();
					}
					
					
					case 1763375486:
					{
						return this.readByte();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
	}
}


